### ISSUE TITLE
DOMParser is not defined

### ISSUE THREAD

**Issue by BugDiver** [andreas-ku/taiko-accessibility#1]
While running taiko tests I get this error

```
DOMParser is not defined
```

### Steps to replicate

* `mkdir foo`
* `cd foo`
* `npm init -y`
* `npm install taiko taiko-accessibility`
* `./node_modules/.bin/taiko`
* `openBrowser()`
* `goto('gauge.org')`
* `accessibility.runAudit()`

```
> accessibility.runAudit()
Thrown:
DOMParser is not defined
```

**Comment by BugDiver** [comment]
After some more research, I found out that It works perfectly when used with `jest` runner.
But when used with `taiko` runner or in `taiko` REPL it does not work. 

My findings
* `DOMParser` is not a `nodejs` API, it's available in browser.
* jest usages `jest-environment-jsdom` which usages `jsdom` (the nodejs implementation to DOM and exposes `DOMParser`), and that's how the plugin get access to DOMParser.

**Comment by andreas-ku** [comment]
Thanks for investigating and please excuse the late reply!

Would it be possible to expose Chrome's DOMParser API from Taiko to be accessible for plugins? That would be the best solution I feel.

**Comment by BugDiver** [comment]
@andreas-ku All the communication between Chrome and the CDP connection is JSON based. So my guess is only serializable things can be shared. I'm not sure if there is a way to access the Chrome's DOMParser and pass it.
I might be wrong, I have not done any analysis about that. You can definitely give it a shot.

**Comment by andreas-ku** [comment]
@BugDiver sorry for coming back to you so late. Can you upgrade to 0.3.0 and try again? It works now for me following your instructions.

I am now calling the Axe script from the browser using Chrome DevTools protocol. So the DOM parsing is not needed anymore, which should make the plugin agnostic of the runner.

![Screen Shot 2020-04-26 at 19 00 02](https://user-images.githubusercontent.com/1586606/80314189-4ce1f900-87f0-11ea-8135-ad010e9f9951.png)

**Comment by BugDiver** [comment]
Now Works as expected.
