### ISSUE TITLE
unable to run the runAudit() method in gauge using taiko

### ISSUE THREAD

**Issue by harimadusumilli** [andreas-ku/taiko-accessibility#12]
Hello Support,

This is my code snippet and its the last step of my code.

I am using Gauge and Taiko

const {openBrowser, goto, currentURL,write, click, link, into, textBox, button,closeBrowser, waitFor,accessibility } = require('taiko');

step("The Inside Page should display names containing employee name", async function() {
    
      //console.log(await link(gauge.dataStore.scenarioStore.get('search_name')).text());
      
      assert.equal(await link(gauge.dataStore.scenarioStore.get('search_name')).exists(), true);
      gauge.screenshot();
      await click(link(gauge.dataStore.scenarioStore.get('search_name')));
      const audit = await accessibility.runAudit();
      assert.equal(audit.violations.length,0);
      await closeBrowser();
});

The error I get is as follows 
 ## US80682 - Search using a valid name        
      * Launch Travelers Inside App with the following url: "https://inside.here.travp.net/"     ...[PASS]
      * Key in valid employee name: "Hari" and search    ...[PASS]
      * The Inside Page should display names containing employee name    ...[FAIL]
        
        Failed Step: The Inside Page should display names containing employee name
        Specification: specs\search_travelers.spec:11
        Error Message: {}
        Stacktrace: 
        TypeError: Cannot read property 'runAudit' of undefined

The version of Gauge and plugins installed are as given below:
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
dotnet (0.1.3)
html-report (4.0.9)
js (2.3.7)
json-report (0.3.3)
screenshot (0.0.1)
xml-report (0.2.3)

**Comment by andreas-ku** [comment]
I am not using Gauge myself, but this looks like `taiko-accessibility` is missing as dependency in your package.json

**Comment by andreas-ku** [comment]
Can this issue be closed?
